language: c

sudo: false

os:
  - linux

dist: xenial

addons:
  apt:
    packages:
      - autoconf
      - libncurses-dev
      - build-essential
      - libssl-dev
      - libwxgtk3.0-dev
      - libglu1-mesa-dev
      - default-jdk
      - g++
      - xsltproc
      - libxml2-utils

matrix:
  include:
    - name: Linux-ARM64-SmokeTest
      arch: arm64
      script:
        - ./scripts/build-otp
        - ./otp_build tests
        - ./scripts/run-smoke-tests

before_script:
  - set -e
  - export ERL_TOP=$PWD
  - export PATH=$ERL_TOP/bin:$PATH
  - export ERL_LIBS=''
  - export MAKEFLAGS=-j4
